### ISSUE TITLE
Deploy failing

### ISSUE THREAD

**Issue by Ajedi32** [metalsmith/metalsmith.io#217]
Not sure if this is just a temporary issue with Heroku or Travis, but the automated deploy [seems to be failing at the moment](https://travis-ci.org/metalsmith/metalsmith.io/jobs/175746811):

```
Installing deploy dependencies
Fetching: multi_json-1.12.1.gem (100%)
Successfully installed multi_json-1.12.1
Fetching: excon-0.54.0.gem (100%)
Successfully installed excon-0.54.0
Fetching: heroku-api-0.4.2.gem (100%)
Successfully installed heroku-api-0.4.2
3 gems installed
Fetching: rendezvous-0.1.2.gem (100%)
Successfully installed rendezvous-0.1.2
1 gem installed
dpl.2
Preparing deploy
authenticated as andyjiang@gmail.com
checking for app 'metalsmith'
found app 'metalsmith'
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): e0a08ff Merge pull request #216 from arccoza/master
HEAD is now at e0a08ff Merge pull request #216 from arccoza/master
dpl.3
Deploying application
creating application archive
uploading application archive
triggering new deployment
curl: (18) transfer closed with outstanding read data remaining
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
heroku build still pending
Already up-to-date!
# HEAD detached at e0a08ff
nothing to commit, working directory clean
Dropped refs/stash@{0} (46643e03db88ec3061301fe6ee96f36cd85e4920)
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:11:in `response_call': Expected([200]) <=> Actual(503 Service Unavailable) (Heroku::API::Errors::ErrorWithResponse)
body: "{\"id\":\"unavailable\",\"message\":\"Service temporarily unavailable. Please try again later.\"}"
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.54.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.54.0/lib/excon/connection.rb:388:in `response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/excon-0.54.0/lib/excon/connection.rb:252:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/heroku-api-0.4.2/lib/heroku/api.rb:84:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/api.rb:79:in `get'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/api.rb:41:in `block in verify_build'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/api.rb:40:in `loop'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/api.rb:40:in `verify_build'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/api.rb:14:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider.rb:145:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider.rb:145:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/provider/heroku/generic.rb:57:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.8.24/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by Ajedi32** [comment]
Yeah, looks like it was just a temporary issue with Heroku. Just triggered a rebuild and everything worked fine...
